/** Exam JSON `category` 키 → 한글 표기 */
export const CATEGORY_LABELS: Record<string, string> = {
  database: "데이터베이스",
  os: "운영체제",
  network: "네트워크",
  "software-engineering": "소프트웨어 공학",
  "data-structures": "자료구조·알고리즘",
  security: "정보 보안",
  "computer-architecture": "컴퓨터 구조",
  "project-management": "프로젝트 관리",
  "safety-law": "산업안전보건법",
  "safety-management": "안전보건관리",
  "risk-assessment": "위험성평가",
  "industrial-health": "산업보건",
  "chemical-safety": "화학물질·MSDS",
  "machinery-safety": "기계·설비 안전",
  "electrical-safety": "전기 안전",
  "fire-explosion": "화기·화재·폭발",
  "confined-space": "밀폐공간",
  ppe: "보호구",
  psm: "PSM·중대재해 예방",
  ergonomics: "인간공학·근골격계",
  "construction-law": "건설·산업안전 법령",
  "construction-mgmt": "건설현장 안전보건관리",
  "construction-risk": "위험성평가(건설)",
  "construction-scaffold": "비계·거푸집·가설",
  "construction-excavation": "굴착·가시설",
  "construction-electrical": "건설 전기·감전 예방",
  "construction-machinery": "건설기계·양중",
  "construction-demolition": "해체공사",
  "construction-fire": "화재·소방(건설)",
  "construction-health": "건설 보건",
  "construction-confined": "밀폐·동바리·지하 작업",
  "construction-ppe": "보호구(건설)",
  "electro-magnetics": "전기자기학",
  "power-engineering": "전력공학",
  "electrical-machines": "전기기기",
  "circuits-control": "회로이론 및 제어공학",
  "electrical-installation": "전기설비",
};

export function getCategoryDisplayName(key: string): string {
  return CATEGORY_LABELS[key] ?? key;
}
